"use strict";
const electron = require("electron");
electron.contextBridge.exposeInMainWorld("database", {
  testConnection: () => electron.ipcRenderer.invoke("db:testConnection"),
  fetchTableData: (tableName) => electron.ipcRenderer.invoke("db:fetchTableData", tableName),
  fetchExhibitors: (segment, limit = 200, person = "exhibitor") => electron.ipcRenderer.invoke("db:fetchExhibitors", segment, limit, person),
  login: (payload) => electron.ipcRenderer.invoke("db:login", payload),
  userHints: () => electron.ipcRenderer.invoke("db:userHints"),
  findCompany: (company) => electron.ipcRenderer.invoke("db:findCompany", company),
  saveAddData: (payload) => electron.ipcRenderer.invoke("db:saveAddData", payload),
  importGabungExcel: (payload) => electron.ipcRenderer.invoke("db:importGabungExcel", payload),
  updateAddData: (id, payload) => electron.ipcRenderer.invoke("db:updateAddData", id, payload),
  deleteAddData: (ids) => electron.ipcRenderer.invoke("db:deleteAddData", ids),
  reportLabelVisitor: (filter) => electron.ipcRenderer.invoke("report:labelvisitor", filter),
  reportLabelGover: (filter) => electron.ipcRenderer.invoke("report:labelgover", filter),
  reportLabelOptions: () => electron.ipcRenderer.invoke("report:labeloptions"),
  reportLabelVisitorPdf: (filter) => electron.ipcRenderer.invoke("report:labelvisitor:pdf", filter),
  reportLabelVisitorExcel: (filter) => electron.ipcRenderer.invoke("report:labelvisitor:excel", filter),
  reportLabelVisitorWord: (filter) => electron.ipcRenderer.invoke("report:labelvisitor:word", filter),
  reportLabelVisitorExportSave: (filter) => electron.ipcRenderer.invoke("report:labelvisitor:export-save", filter),
  reportLabelGoverPdf: (filter) => electron.ipcRenderer.invoke("report:labelgover:pdf", filter),
  reportLabelGoverExcel: (filter) => electron.ipcRenderer.invoke("report:labelgover:excel", filter),
  reportLabelGoverWord: (filter) => electron.ipcRenderer.invoke("report:labelgover:word", filter),
  reportLabelGoverExportSave: (filter) => electron.ipcRenderer.invoke("report:labelgover:export-save", filter),
  reportPerusahaan: (filter) => electron.ipcRenderer.invoke("report:perusahaan", filter),
  reportGovernment: (filter) => electron.ipcRenderer.invoke("report:government", filter),
  reportPerusahaanPdf: (filter) => electron.ipcRenderer.invoke("report:perusahaan:pdf", filter),
  reportPerusahaanExcel: (filter) => electron.ipcRenderer.invoke("report:perusahaan:excel", filter),
  reportPerusahaanWord: (filter) => electron.ipcRenderer.invoke("report:perusahaan:word", filter),
  reportPerusahaanExportSave: (filter) => electron.ipcRenderer.invoke("report:perusahaan:export-save", filter),
  reportGovernmentPdf: (filter) => electron.ipcRenderer.invoke("report:government:pdf", filter),
  reportGovernmentExcel: (filter) => electron.ipcRenderer.invoke("report:government:excel", filter),
  reportGovernmentWord: (filter) => electron.ipcRenderer.invoke("report:government:word", filter),
  reportGovernmentExportSave: (filter) => electron.ipcRenderer.invoke("report:government:export-save", filter),
  reportJumlahPerusahaan: (filter) => electron.ipcRenderer.invoke("report:jumlah-perusahaan", filter),
  reportJumlahGovernment: (filter) => electron.ipcRenderer.invoke("report:jumlah-government", filter),
  reportJumlahPerusahaanPdf: (filter) => electron.ipcRenderer.invoke("report:jumlah-perusahaan:pdf", filter),
  reportJumlahPerusahaanExcel: (filter) => electron.ipcRenderer.invoke("report:jumlah-perusahaan:excel", filter),
  reportJumlahPerusahaanWord: (filter) => electron.ipcRenderer.invoke("report:jumlah-perusahaan:word", filter),
  reportJumlahPerusahaanExportSave: (filter) => electron.ipcRenderer.invoke("report:jumlah-perusahaan:export-save", filter),
  reportJumlahGovernmentPdf: (filter) => electron.ipcRenderer.invoke("report:jumlah-government:pdf", filter),
  reportJumlahGovernmentExcel: (filter) => electron.ipcRenderer.invoke("report:jumlah-government:excel", filter),
  reportJumlahGovernmentWord: (filter) => electron.ipcRenderer.invoke("report:jumlah-government:word", filter),
  reportJumlahGovernmentExportSave: (filter) => electron.ipcRenderer.invoke("report:jumlah-government:export-save", filter)
});
