CREATE TABLE IF NOT EXISTS "AUDIT_LOG" (
  "ID" SERIAL PRIMARY KEY,
  "USERNAME" VARCHAR(50),
  "ACTION" VARCHAR(20) NOT NULL,
  "PAGE" VARCHAR(100),
  "SUMMARY" VARCHAR(255),
  "DATA" JSONB,
  "CREATED_AT" TIMESTAMP NOT NULL DEFAULT NOW()
);
