export type ComboFieldName =
  | 'mainActive'
  | 'business'
  | 'exhibitor'
  | 'visitor'
  | 'typeOfVisitor'
  | 'specialInvitationIndoDefence'
  | 'openingCeremony'
  | 'kartuUcapan'
  | 'poster'
  | 'tidakDikirim'

export type ComboOptions = Record<ComboFieldName, string[]>

export const comboFields: ComboFieldName[] = [
  'mainActive',
  'business',
  'exhibitor',
  'visitor',
  'typeOfVisitor',
  'specialInvitationIndoDefence',
  'openingCeremony',
  'kartuUcapan',
  'poster',
  'tidakDikirim',
]

export const comboOptions: ComboOptions = {
  mainActive: [
    'Agent',
    'Association',
    'Distributor',
    'Embassy',
    'Export & Import',
    'Exporter',
    'Government',
    'Importer',
    'Manufacturer, Industry',
    'Media',
    'Military',
    'Others',
    'POLRI',
    'Producer',
    'Services',
    'Supplier',
    'Trade',
    'Trading, Retail',
    'University, Education',
  ],
  business: [
    'Additives',
    'Aerospace',
    'Aircraft',
    'Ammunition',
    'Aquaculture',
    'Armor',
    'Army',
    'Artillery',
    'Audio',
    'Automation',
    'Aviation',
    'Biotech',
    'Breeding',
    'Cages',
    'Cattle',
    'Chicken, Broiler',
    'Coldchain',
    'Communication',
    'Contractor',
    'Cybersecurity',
    'Dairy',
    'Defence',
    'Desalination',
    'Digital',
    'Drainage',
    'Drone',
    'Electronics',
    'Engineering',
    'Environmental',
    'Equipment',
    'Exhibition',
    'Farm',
    'Feed',
    'Filtration',
    'Firearms',
    'Fisheries',
    'Furniture',
    'Genetics',
    'Goat',
    'Health',
    'Helicopter',
    'Horticulture',
    'Husbandry',
    'Hydrology',
    'Infantry',
    'Infrastructure',
    'Innovation',
    'IoT',
    'Irrigation',
    'Livestock',
    'Logistics',
    'Mabel',
    'Machinery',
    'Maintenance',
    'Maritime',
    'Medicine',
    'Membrane',
    'Metering',
    'Missiles',
    'Monitoring',
    'Naval',
    'Nutrition',
    'Packaging',
    'Pharmaceutical',
    'Pipe',
    'Plantation',
    'Poultry',
    'Processing',
    'Pump',
    'Radar',
    'Recycling',
    'Robotics',
    'Sanitation',
    'Satellite',
    'SDTI',
    'Seaweed',
    'Security',
    'Seed',
    'Sewage',
    'Sheep',
    'Simulation',
    'Slaughter',
    'Smart',
    'Sonar',
    'Storage',
    'Surveillance',
    'Sustainability',
    'Tank',
    'Technology',
    'Thermal',
    'Training',
    'Treatment',
    'Unmanned',
    'Vaccine',
    'Valve',
    'Vehicle',
    'Ventilation',
    'Veterinary',
    'Waste',
    'Water',
    'Weapons',
  ],
  exhibitor: [
    'Defence',
    'Aerospace',
    'Marine',
    'Water',
    'Waste',
    'Renergy',
    'Smart City',
    'Security',
    'Firex',
    'Livestock',
    'Agrotech',
    'Fisheries',
    'Vet',
    'Feed',
    'Dairy',
    'Horticulture',
  ],
  visitor: [
    'Defence',
    'Aerospace',
    'Marine',
    'Water',
    'Waste',
    'Renergy',
    'Smart City',
    'Security',
    'Firex',
    'Livestock',
    'Agrotech',
    'Fisheries',
    'Vet',
    'Feed',
    'Dairy',
    'Horticulture',
  ],
  typeOfVisitor: [
    'Government',
    'VVIP',
    'VIP Defence',
    'VIP Aerospace',
    'VIP Marine',
    'VIP Water',
    'VIP Waste',
    'VIP Smart City',
    'VIP Renergy',
    'VIP Security',
    'VIP Firex',
    'VIP Livestock',
    'VIP Fisheries',
    'VIP Agrotech',
    'VIP Vet',
    'VIP Feed',
    'VIP Dairy',
    'VIP Horticulture',
  ],
  specialInvitationIndoDefence: [
    'Welcoming',
    'Off Lunch',
    'Society Lunch',
    'Demo 1',
    'Demo 2',
    'Demo 3',
    'Seminar 1',
    'Seminar 2',
    'Seminar 3',
    'Seminar 4',
    'Courtessy Call',
    'Courtessy Visit',
    'Visit Call',
    'TPP 1',
    'TPP 2',
    'TPP 3',
    'TPP 4',
  ],
  openingCeremony: [
    'OC DEFENCE',
    'OC MARINE',
    'OC AEROSPACE',
    'OC WATER JKT',
    'OC WATERS BY',
    'OC WASTE',
    'OC SMART CITY',
    'OC RENERGY',
    'OC SECURITY',
    'OC FIREX',
    'OC LIVESTOCK JKT',
    'OC LIVESTOCK SBY',
    'OC AGROTECH',
    'OC FISHERIES',
    'OC VET',
    'OC FEED',
    'OC DAIRY',
    'OC HORTICULTURE',
  ],
  kartuUcapan: ['Kalender', 'Parcel', 'Tahun Baru', 'Lebaran'],
  poster: ['IDD', 'IDA', 'IDM', 'IDW', 'ISF', 'ISC', 'IDL'],
  tidakDikirim: ['IDD', 'IDW JKT', 'IDW SBY', 'IDL JKT', 'IDL SBY'],
}

export const code2Options = ['OK', 'ERROR', 'RESIGN']
export const code3Options = ['BLM', 'TDK', 'TUNDA']
