export type ComboFieldName =
  | 'mainActive'
  | 'business'
  | 'exhibitor'
  | 'visitor'
  | 'typeOfVisitor'
  | 'specialInvitationIndoDefence'
  | 'openingCeremony'
  | 'kartuUcapan'
  | 'poster'
  | 'tidakDikirim'

export type ComboOptions = Record<ComboFieldName, string[]>

export const comboFields: ComboFieldName[] = [
  'mainActive',
  'business',
  'exhibitor',
  'visitor',
  'typeOfVisitor',
  'specialInvitationIndoDefence',
  'openingCeremony',
  'kartuUcapan',
  'poster',
  'tidakDikirim',
]

export const comboOptions: ComboOptions = {
  mainActive: [
    'Agent',
    'Association',
    'Distributor',
    'Embassy',
    'Export & Import',
    'Exporter',
    'Government',
    'Importer',
    'Manufacturer, Industry',
    'Media',
    'Military',
    'Others',
    'POLRI',
    'Producer',
    'Services',
    'Supplier',
    'Trade',
    'Trading, Retail',
    'University, Education',
  ],
  business: [
    'Academy',
    'Accomodation',
    'Additives',
    'Advertising',
    'Aerator',
    'Aeronautical',
    'Aerospace',
    'Agribusiness',
    'Agriculture',
    'Agroindustry',
    'AI',
    'Air',
    'Airbone',
    'Airport',
    'Aircraft',
    'Ammunition',
    'Animal',
    'Anti Drone',
    'Aquaculture',
    'Aquatic',
    'Armor',
    'Army',
    'Artillery',
    'Association',
    'Audio',
    'Automation',
    'Automotive',
    'Autonomous',
    'Aviation',
    'Avionics',
    'Bank',
    'Biotech',
    'Breeding',
    'Business',
    'Cages',
    'Cattle',
    'CCTV',
    'Chemicals',
    'Chicken Broiler',
    'Clean',
    'Coldchain',
    'Communication',
    'Compressor',
    'Consultant',
    'Contractor',
    'Cybersecurity',
    'Dairy',
    'Defence',
    'Desalination',
    'Digital',
    'Distributor',
    'Drainage',
    'Drone',
    'Education',
    'Electronics',
    'Energy',
    'Engine',
    'Engineering',
    'Environmental',
    'Equipment',
    'Exhibition',
    'Farm',
    'Feed',
    'Fertilize',
    'Filtration',
    'Fire',
    'Firearms',
    'Fisheries',
    'Force',
    'Furniture',
    'Gas',
    'Genetics',
    'Goat',
    'GOV',
    'Grain',
    'Hatchery',
    'Health',
    'Helicopter',
    'Home Appliance',
    'Horticulture',
    'Husbandry',
    'Hydrology',
    'Hydroponic',
    'Incenerator',
    'Industry',
    'Infantry',
    'Infrastructure',
    'Innovation',
    'Insurance',
    'IoT',
    'Irrigation',
    'IT',
    'Land System',
    'Layer',
    'Livestock',
    'Logistics',
    'Mabel',
    'Machinery',
    'Magazine',
    'Management',
    'Manufacture',
    'Marine',
    'Measurement',
    'Mechatronics',
    'Medical',
    'Membrane',
    'Metering',
    'Military',
    'Missiles',
    'Monitoring',
    'MRO',
    'Naval',
    'Navigation',
    'Network',
    'Nutrition',
    'Optics',
    'Packaging',
    'Palm Oil',
    'Pest Control',
    'Pharmaceutical',
    'Pipe',
    'Plantation',
    'Platform',
    'Plumbing',
    'Poultry',
    'Processing',
    'Products',
    'Pump',
    'Purify',
    'Radars',
    'Recycling',
    'Renewable',
    'Retail',
    'Robotics',
    'Safety',
    'Sanitation',
    'Satellite',
    'SDTI',
    'Seaweed',
    'Security',
    'Seed',
    'Services',
    'Sewage',
    'Sheep',
    'Simulation',
    'Slaughter',
    'Smart',
    'Solutions',
    'Sonar',
    'Steel',
    'Storage',
    'Surveillance',
    'Sustainability',
    'Systems',
    'Tank',
    'Technology',
    'Textile',
    'Thermal',
    'Training',
    'Tractor',
    'Transportation',
    'Treatment',
    'UAS, UAV',
    'Vaccine',
    'Valve',
    'Vehicle',
    'Ventilation',
    'Veterinary',
    'Waste',
    'Water',
    'Waterwheel',
    'Water Tank',
    'Weapons',
    'WTP',
    'WWTP',
  ],
  exhibitor: [
    'Defence',
    'Aerospace',
    'Marine',
    'Water',
    'Waste',
    'Renergy',
    'Smart City',
    'Security',
    'Firex',
    'Livestock',
    'Agrotech',
    'Fisheries',
    'Vet',
    'Feed',
    'Dairy',
    'Horticulture',
  ],
  visitor: [
    'Defence',
    'Aerospace',
    'Marine',
    'Water',
    'Waste',
    'Renergy',
    'Smart City',
    'Security',
    'Firex',
    'Livestock',
    'Agrotech',
    'Fisheries',
    'Vet',
    'Feed',
    'Dairy',
    'Horticulture',
  ],
  typeOfVisitor: [
    'Government',
    'VVIP',
    'VIP Defence',
    'VIP Aerospace',
    'VIP Marine',
    'VIP Water',
    'VIP Waste',
    'VIP Smart City',
    'VIP Renergy',
    'VIP Security',
    'VIP Firex',
    'VIP Livestock',
    'VIP Fisheries',
    'VIP Agrotech',
    'VIP Vet',
    'VIP Feed',
    'VIP Dairy',
    'VIP Horticulture',
  ],
  specialInvitationIndoDefence: [
    'Welcoming',
    'Off Lunch',
    'Society Lunch',
    'Demo 1',
    'Demo 2',
    'Demo 3',
    'Seminar 1',
    'Seminar 2',
    'Seminar 3',
    'Seminar 4',
    'Courtessy Call',
    'Courtessy Visit',
    'Visit Call',
    'TPP 1',
    'TPP 2',
    'TPP 3',
    'TPP 4',
  ],
  openingCeremony: [
    'OC DEFENCE',
    'OC MARINE',
    'OC AEROSPACE',
    'OC WATER JKT',
    'OC WATERS BY',
    'OC WASTE',
    'OC SMART CITY',
    'OC RENERGY',
    'OC SECURITY',
    'OC FIREX',
    'OC LIVESTOCK JKT',
    'OC LIVESTOCK SBY',
    'OC AGROTECH',
    'OC FISHERIES',
    'OC VET',
    'OC FEED',
    'OC DAIRY',
    'OC HORTICULTURE',
  ],
  kartuUcapan: ['Kalender', 'Parcel', 'Tahun Baru', 'Lebaran'],
  poster: ['IDD', 'IDA', 'IDM', 'IDW', 'ISF', 'ISC', 'IDL'],
  tidakDikirim: ['IDD', 'IDW JKT', 'IDW SBY', 'IDL JKT', 'IDL SBY'],
}

export const code2Options = ['OK', 'ERROR', 'RESIGN']
export const code3Options = ['BLM', 'TDK', 'TUNDA']
