export const exhibitorFlagMap: Record<string, string> = {
  Defence: 'EXHDEFENCE',
  Aerospace: 'EXHAERO',
  Marine: 'EXHMARINE',
  Water: 'EXHWATER',
  Waste: 'EXHWASTE',
  Renergy: 'EXHENERGY',
  'Smart City': 'EXHSMART',
  Security: 'EXHSECURE',
  Firex: 'EXHFIRE',
  Livestock: 'EXHLIVES',
  Agrotech: 'EXHAGRITECH',
  Fisheries: 'EXHFISH',
  Vet: 'EXHINDOVET',
  Feed: 'EXHFEED',
  Dairy: 'EXHDAIRY',
  Horticulture: 'EXHHORTI',
}

export const visitorFlagMap: Record<string, string> = {
  Defence: 'VISDEFENCE',
  Aerospace: 'VISAERO',
  Marine: 'VISMARINE',
  Water: 'VISWATER',
  Waste: 'VISWASTE',
  Renergy: 'VISENERGY',
  'Smart City': 'VISSMART',
  Security: 'VISSECURE',
  Firex: 'VISFIRE',
  Livestock: 'VISLIVES',
  Agrotech: 'VISAGRITECH',
  Fisheries: 'VISFISH',
  Vet: 'VISINDOVET',
  Feed: 'VISFEED',
  Dairy: 'VISDAIRY',
  Horticulture: 'VISHORTI',
}

export const typeOfVisitorFlagMap: Record<string, string> = {
  Government: 'GOVER',
  VVIP: 'VVIP',
  'VIP Aerospace': 'VIPAERO',
  'VIP Defence': 'VID',
  'VIP Marine': 'VIPMARINE',
  'VIP Water': 'VIW',
  'VIP Smart City': 'VIPIISMEX',
  'VIP Renergy': 'VIPIDRE',
  'VIP Livestock': 'VIL',
  'VIP Security': 'VIS',
  'VIP Agrotech': 'VIPAGRI',
  'VIP Vet': 'VIPINDOVET',
  'VIP Waste': 'VIWASTE',
  'VIP Firex': 'VIFIRE',
  'VIP Fisheries': 'VIFISH',
  'VIP Feed': 'VIFEED',
  'VIP Dairy': 'VIDAIRY',
  'VIP Horticulture': 'VIHORTI',
}

export const invitationFlagMap: Record<string, string> = {
  Welcoming: 'WELCOMING',
  'Off Lunch': 'OFFLUNCH',
  'Society Lunch': 'SOCIETY',
  'Demo 1': 'DEMO1',
  'Demo 2': 'DEMO2',
  'Demo 3': 'DEMO3',
  'Seminar 1': 'SEMINAR1',
  'Seminar 2': 'SEMINAR2',
  'Seminar 3': 'SEMINAR3',
  'Seminar 4': 'SEMINAR4',
  'Courtessy Call': 'COURTESYCALL',
  'Courtessy Visit': 'COURTESYVISIT',
  'Visit Call': 'VISITCALL',
  'TPP 1': 'TPP1',
  'TPP 2': 'TPP2',
  'TPP 3': 'TPP3',
  'TPP 4': 'TPP4',
}

export const openingCeremonyFlagMap: Record<string, string> = {
  'OC DEFENCE': 'OCD',
  'OC MARINE': 'OCMARINE',
  'OC AEROSPACE': 'OCAERO',
  'OC WATER JKT': 'OCWJKT',
  'OC WATER SBY': 'OCWSBY',
  'OC WASTE': 'OCWASTE',
  'OC SMART CITY': 'OCSMART',
  'OC RENERGY': 'OCENERGY',
  'OC SECURITY': 'OCS',
  'OC FIREX': 'OCFIRE',
  'OC LIVESTOCK JKT': 'OCLJKT',
  'OC LIVESTOCK SBY': 'OCLSBY',
  'OC AGROTECH': 'OCAGRI',
  'OC FISHERIES': 'OCFISH',
  'OC VET': 'OCINDOVET',
  'OC FEED': 'OCFEED',
  'OC DAIRY': 'OCDAIRY',
  'OC HORTICULTURE': 'OCHORTI',
}

export const kartuUcapanFlagMap: Record<string, string> = {
  Kalender: 'KALENDER',
  Lebaran: 'LEBARAN',
  Parcel: 'PARCEL',
  'Tahun Baru': 'TAHUNBARU',
}

export const posterFlagMap: Record<string, string> = {
  IDD: 'PTRD',
  IDA: 'PTRAERO',
  IDM: 'PTRMARINE',
  IDW: 'PTRW',
  ISF: 'PTRS',
  ISC: 'PTRIISMEX',
  IDL: 'PTRL',
}

export const tidakKirimFlagMap: Record<string, string> = {
  IDD: 'TDKKRMIDD',
  'IDW JKT': 'TDKKRMIDWJKT',
  'IDW SBY': 'TDKKRMIDWSBY',
  'IDL JKT': 'TDKKRMIDLJKT',
  'IDL SBY': 'TDKKRMIDLSBY',
}
