export const provinceCityMap: Record<string, string[]> = {
  DIA: [
    'Aceh',
    'Aceh Besar',
    'Aceh Jaya',
    'Aceh Singkil',
    'Aceh Tamiang',
    'Banda Aceh',
    'Bener Meriah',
    'Bireun',
    'Blang Pidie',
    'Calang',
    'Gayo Lues',
    'Kutacane',
    'Langsa Kota',
    'Lhokseumawe Kota',
    'Meulaboh',
    'Nagan Raya',
    'Pidie',
    'Pidie Jaya',
    'Sabang Kota',
    'Sigli',
    'Singkil',
    'Simulue',
    'Subulussalam',
    'Tapaktuan',
  ],
  Sumut: [
    'Asahan',
    'Batubara',
    'Binjai',
    'Dairi',
    'Deli Serdang',
    'Gunung Sitoli',
    'Humbang Hasundutan',
    'Karo',
    'Labuhanbatu',
    'Langkat',
    'Mandailing Natal',
    'Medan',
    'Nias',
    'Padang Lawas',
    'Padang Sidempuan',
    'Pakpak Bharat',
    'Pemantangsiantar',
    'Samosir',
    'Serdang Bedagai',
    'Sibolga',
    'Simalungun',
    'Tanjung Balai',
    'Tapanuli',
    'Tebing Tinggi',
    'Toba Samosir',
  ],
  Sumbar: [
    'Agam',
    'Bukittinggi',
    'Dharmasraya',
    'Kep. Mentawai',
    'Lima Puluh Kota',
    'Padang',
    'Padangpanjang',
    'Pariaman',
    'Pasaman',
    'Pasaman Barat',
    'Payakumbuh',
    'Pesisir Selatan',
    'Sawahlunto',
    'Sijunjung',
    'Solok',
    'Tanah Datar',
  ],
  Sumsel: [
    'Bangka Belitung',
    'Banyuasin',
    'Empat Lawang',
    'Lahat',
    'Lubuklinggau',
    'Muara Enim',
    'Musi Banyuasin',
    'Musi Rawas',
    'Ogan Ilir',
    'Ogan Komering Ilir',
    'Ogan Komering Ulu',
    'Pagar Alam',
    'Palembang',
    'Prabumulih',
  ],
  Riau: [
    'Batam',
    'Bengkalis',
    'Dumai',
    'Indragiri Hilir',
    'Indragiri Hulu',
    'Kampar',
    'Kep. Meranti',
    'Kuantan Singingi',
    'Pangkal Pinang',
    'Pekanbaru',
    'Pelalawan',
    'Rokan Hilir',
    'Rokan Hulu',
    'Siak',
  ],
  'Kep. Riau': ['Batam', 'Bintan', 'Karimun', 'Kep. Anambas', 'Lingga', 'Natuna', 'Tanjung Pinang'],
  Jambi: [
    'Batang Hari',
    'Bungo',
    'Jambi Kota',
    'Kerinci',
    'Merangin',
    'Muaro Jambi',
    'Sarolangun',
    'Sungaipenuh',
    'Tanjung Jabung Barat',
    'Tanjung Jabung Timur',
    'Tebo',
  ],
  Bengkulu: ['Bengkulu', 'Kaur', 'Kepahiang', 'Lebong', 'Mukomuko', 'Rejang Lebong', 'Seluma'],
  Lampung: [
    'Bandar Lampung',
    'Lampung',
    'Mesuji',
    'Metro',
    'Pesawaran',
    'Pringsewu',
    'Tanggamus',
    'Tulang Bawang',
    'Way Kanan',
  ],
  DKI: ['Jakarta', 'Kepulauan Seribu'],
  Jabar: [
    'Bandung',
    'Banjar',
    'Banten',
    'Ciamis',
    'Cianjur',
    'Cikampek',
    'Cilegon',
    'Cimahi',
    'Cirebon',
    'Garut',
    'Indramayu',
    'Karawang',
    'Kuningan',
    'Majalengka',
    'Pandeglang',
    'Purwakarta',
    'Serang',
    'Subang',
    'Sukabumi',
    'Sumedang',
    'Tasikmalaya',
  ],
  Jatim: [
    'Ambulu',
    'Babat',
    'Bangkalan',
    'Banyuwangi',
    'Blitar',
    'Bojonegoro',
    'Bondowoso',
    'Gresik',
    'Jember',
    'Jombang',
    'Kediri',
    'Kep. Masalembu',
    'Kertosono',
    'Kota Batu',
    'Lamongan',
    'Lumajang',
    'Madiun',
    'Magetan',
    'Malang',
    'Mojokerto',
    'Nganjuk',
    'Ngawi',
    'Pacitan',
    'Pamekasan',
    'Pare',
    'Pasuruan',
    'Ponorogo',
    'Probolinggo',
    'Sampang',
    'Sidoarjo',
    'Situbondo',
    'Sumenep',
    'Surabaya',
    'Trenggalek',
    'Tuban',
    'Tulungagung',
  ],
  Botabek: ['Bogor', 'Bekasi', 'Cariu', 'Cibinong', 'Cileungsi', 'Depok', 'Jonggol', 'Tangerang'],
  Jateng: [
    'Banjarnegara',
    'Bantul',
    'Banyumas',
    'Batang',
    'Blora',
    'Boyolali',
    'Brebes',
    'Cilacap',
    'Comal',
    'Demak',
    'Gombong',
    'Grobogan',
    'Gunung Kidul',
    'Jepara',
    'Karanganyar',
    'Kebumen',
    'Kendal',
    'Klaten',
    'Kudus',
    'Kulon Progo',
    'Kutoarjo',
    'Magelang',
    'Pati',
    'Pekalongan',
    'Pemalang',
    'Purbalingga',
    'Purwokerto',
    'Purworejo',
    'Rembang',
    'Salatiga',
    'Semarang',
    'Sleman',
    'Solo',
    'Sragen',
    'Sukoharjo',
    'Surakarta',
    'Tegal',
    'Temanggung',
    'Ungaran',
    'Waleri',
    'Wonogiri',
    'Wonosobo',
    'Yogyakarta',
  ],
  Bali: [
    'Amlapura',
    'Badung',
    'Bali',
    'Bangli',
    'Buleleng',
    'Denpasar',
    'Gianyar',
    'Jembrana',
    'Karangasem',
    'Klungkung',
    'Negara',
    'Nusa Dua',
    'Sanur',
    'Singaraja',
    'Tabanan',
    'Ubud',
  ],
  NTT: [
    'Alor',
    'Atambua',
    'Bajawa',
    'Belu',
    'Ende',
    'Flores',
    'Kefamenanu',
    'Kupang',
    'Larantuka',
    'Lembata',
    'Manggarai',
    'Muamere',
    'Nagekeo',
    'Ngada',
    'Rote Ndao',
    'Sabu Raijua',
    'Sikka',
    'Sumba Barat',
    'Timor Tengah',
  ],
  NTB: ['Alas', 'Bima Kab', 'Bima Kota', 'Dompu', 'Lombok', 'Mataram', 'Selong', 'Sumbawa'],
  Kalbar: [
    'Bengkayang',
    'Kapuas Hulu',
    'Kayong Utara',
    'Ketapang',
    'Kubu Raya',
    'Landak',
    'Melawai',
    'Ngabang',
    'Pontianak',
    'Sambas',
    'Sanggau',
    'Sekadau',
    'Singkawang',
    'Sintang',
  ],
  Kalteng: [
    'Barito',
    'Gunung Mas',
    'Kapuas',
    'Katingan',
    'Kotawaringin',
    'Lamandau',
    'Murung Raya',
    'Palangkaraya',
    'Pulang Pisau',
    'Sampit',
    'Seruyan',
    'Sukamara',
  ],
  Kalsel: [
    'Balanngan',
    'Banjar',
    'Banjarbaru',
    'Banjarmasin',
    'Barito Kuala',
    'Hulu Sungai',
    'Kotabaru',
    'Sinjai',
    'Tabalong',
    'Tanah Bambu',
    'Tanah Laut',
    'Tapin',
  ],
  Kaltara: ['Bunyu', 'Malinau', 'Nunukan', 'Tana Tidung', 'Tanjungselor', 'Tarakan'],
  Kaltim: [
    'Balikpapan',
    'Berau',
    'Bontang',
    'Kutai Barat',
    'Kutai Kartanegara',
    'Kutai Timur',
    'Paser',
    'Penajam Paser Utr',
    'Samarinda',
    'Tenggarong',
  ],
  Sulut: [
    'Amurang',
    'Bitung',
    'Bolaang Mangondow',
    'Kep. Sangihe',
    'Kep. Siau Tangulandang Biaro',
    'Kep. Talaud',
    'Kotamobagu',
    'Manado',
    'Minahasa',
    'Tahuna',
    'Tomohon',
    'Tondano',
  ],
  Sulbar: ['Majene', 'Mamasa', 'Mamuju', 'Mamuju Utara', 'Polewali Mandar'],
  Sulteng: [
    'Ampana',
    'Banggai',
    'Banggai Kep.',
    'Buol',
    'Donggala',
    'Luwuk',
    'Morowali',
    'Palu',
    'Parigi Mountong',
    'Poso',
    'Sigi',
    'Tentena',
    'Tojo Una-una',
    'Toli-Toli',
  ],
  Sulsel: [
    'Bantaeng',
    'Barru',
    'Bone',
    'Bulukumba',
    'Enrekang',
    'Gowa',
    'Jenepronto',
    'Kep. Selayar',
    'Luwu',
    'Makale',
    'Makassar',
    'Malili',
    'Malino',
    'Maros',
    'Masamba',
    'Palopo',
    'Pangkajane dan Kep.',
    'Pare-Pare',
    'Pinrang',
    'Rantepao',
    'Sidenreng Rappang',
    'Sinjai',
    'Soroako',
    'Soppeng',
    'Takalar',
    'Tana Toraja',
    'Toraja Utara',
    'Wajo',
    'Watampone',
  ],
  Sultra: ['Bau-Bau', 'Bombana', 'Buton', 'Kendari', 'Kolaka', 'Konawe', 'Muna', 'Wakatobi'],
  Gorontalo: ['Boalemo', 'Bone Bolango', 'Gorontalo', 'Pohuwanto'],
  Maluku: [
    'Ambon',
    'Bandanaira',
    'Bula',
    'Buru',
    'Buru Selatan',
    'Dobo',
    'Halmahera',
    'Kep. Aru',
    'Kep. Sula',
    'Maluku',
    'Namlea',
    'Pulau Morotai',
    'Seram Bagian Barat',
    'Seram Bagian Timur',
    'Ternate',
    'Tidore Kep.',
    'Tual',
  ],
  Irian: [
    'Asmat',
    'Biak Numfor',
    'Boven Digoel',
    'Deiyai',
    'Dogiyai',
    'Fakfak',
    'Intan Jaya',
    'Jayapura',
    'Jayawijaya',
    'Kaimana',
    'Keerom',
    'Lanny Jaya',
    'Mamberamo Raya',
    'Mamberamo Tengah',
    'Manokwari',
    'Maybrat',
    'Merauke',
    'Mimika',
    'Mippi',
    'Nabire',
    'Nduga',
    'Paniai',
    'Pegunungan Bintang',
    'Puncak',
    'Puncak Jaya',
    'Raja Ampat',
    'Sarmi',
    'Serui',
    'Sorong',
    'Supiori',
    'Tambrauw',
    'Teluk Bintuni',
    'Teluk Wondama',
    'Tempabagapura',
    'Timika',
    'Tolikara',
    'Waropen',
    'Yahukimo',
    'Yalimo',
    'Yapen Waropen',
  ],
  Asia: [
    'Afghanistan',
    'Armenia',
    'Australia',
    'Azerbaijan',
    'Bahrain',
    'Bangladesh',
    'Bhutan',
    'Brunei',
    'Cambodia',
    'China',
    'Georgia',
    'Hong Kong',
    'India',
    'Iran',
    'Iraq',
    'Israel',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Lebanon',
    'Malaysia',
    'Maldives',
    'Mongolia',
    'Myanmar',
    'Nepal',
    'New Zealand',
    'Oman',
    'Pakistan',
    'Papua New Guinea',
    'Philippines',
    'Qatar',
    'Saudi Arabia',
    'Singapore',
    'South Korea',
    'Sri Lanka',
    'Syriah',
    'Taiwan',
    'Tajikistan',
    'Thailand',
    'Timor Leste',
    'Turkmenistan',
    'United Arab Emirates',
    'Uzbekistan',
    'Vietnam',
    'Yemen',
  ],
  Africa: [
    'Algeria',
    'Angola',
    'Benin',
    'Botswana',
    'Burkina Faso',
    'Burundi',
    'Cameroon',
    'Cape Verde',
    'Central African Republic',
    'Chad',
    "Cote d'Ivoire",
    'Djibouti',
    'Egypt',
    'Equatorial Guinea',
    'Eritrea',
    'Ethiopia',
    'Gabon',
    'Ghana',
    'Guinea',
    'Guinea-Bissau',
    'Kenya',
    'Kingdom of Kongo',
    'Lesotho',
    'Liberia',
    'Libya',
    'Madagascar',
    'Malawi',
    'Mali',
    'Mauritania',
    'Mauritius',
    'Morocco',
    'Mozambique',
    'Namibia',
    'Niger',
    'Nigeria',
    'Rwanda',
    'Sao Tome dan Principe',
    'Senegal',
    'Seychelles',
    'Sierra Leone',
    'Somalia',
    'South Africa',
    'South of Sudan',
    'Sudan',
    'Swaziland',
    'Tanzania',
    'The Gambia',
    'Togo',
    'Tunisia',
    'Uganda',
    'Zambia',
    'Zimbabwe',
  ],
  Eropa: [
    'Albania',
    'Andorra',
    'Austria',
    'Azerbaijan',
    'Belarus',
    'Belgium',
    'Bosnia and Herzegovina',
    'Bulgaria',
    'Croatia',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'England',
    'Estonia',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Hungary',
    'Iceland',
    'Italy',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macedonia',
    'Moldova',
    'Malta',
    'Monaco',
    'Montenegro',
    'Netherlands',
    'Norway',
    'Poland',
    'Portugal',
    'Republic of Ireland',
    'Romania',
    'Russia',
    'San Marino',
    'Serbia',
    'Slovakia',
    'Slovenia',
    'Spain',
    'Sweden',
    'Switzerland',
    'Turkey',
    'Ukraine',
    'United Kingdom',
    'Vatican City',
  ],
  USA: [
    'Antigua and Barbuda',
    'Argentina',
    'Bahamas',
    'Barbados',
    'Belize',
    'Bolivia',
    'Brazil',
    'California',
    'Canada',
    'Chile',
    'Colombia',
    'Costa Rica',
    'Cuba',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'El Salvador',
    'Falkland Islands',
    'Grenada',
    'Guatemala',
    'Guyana',
    'Haiti',
    'Honduras',
    'Jamaica',
    'Mexico',
    'Nicaragua',
    'Panama',
    'Paraguay',
    'Peru',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Suriname',
    'Trinidad and Tobago',
    'United States',
    'Uruguay',
    'Venezuela',
  ],
  TUTUP: [],
  PINDAH: [],
}

export const provinceOptions = Object.keys(provinceCityMap)
