export type PageKey =
  | "dashboard"
  | "auditLog"
  | "addData"
  | "exhibitor"
  | "visitor"
  | "importData"
  | "printPerusahaan"
  | "printGovernment"
  | "reportPerusahaan"
  | "reportGovernment"
  | "reportJumlahPerusahaan"
  | "reportJumlahGovernment"
  | "addUser"
  | "changePassword";
