export type PageKey =
  | 'dashboard'
  | 'exhibitor'
  | 'visitor'
  | 'importData'
  | 'printPerusahaan'
  | 'printGovernment'
  | 'reportPerusahaan'
  | 'reportGovernment'
  | 'reportJumlahPerusahaan'
  | 'reportJumlahGovernment'
  | 'addUser'
  | 'changePassword'
