export const endpoints = {
  gabung: {
    list: "/gabung",
    detail: (id: number | string) => `/gabung/${id}`,
    create: "/gabung",
    update: (id: number | string) => `/gabung/${id}`,
    remove: (id: number | string) => `/gabung/${id}`,
    importExcel: "/gabung/import/excel",
    personalPdf: "/gabung/personal-pdf",
    sourceOptions: "/gabung/source-options",
    code1Options: "/gabung/code1-options",
  },
  pengguna: {
    list: "/pengguna",
    detail: (username: string) => `/pengguna/${username}`,
    create: "/pengguna",
    update: (username: string) => `/pengguna/${username}`,
    remove: (username: string) => `/pengguna/${username}`,
    login: "/pengguna/login",
  },
  audit: {
    list: "/audit/logs",
    create: "/audit/logs",
  },
  report: {
    labelVisitor: "/report/labelvisitor",
    labelVisitorPdf: "/report/labelvisitor/print",
    labelVisitorExcel: "/report/labelvisitor/export/excel",
    labelVisitorWord: "/report/labelvisitor/export/word",
    labelGover: "/report/labelgover",
    labelGoverPdf: "/report/labelgover/print",
    labelGoverExcel: "/report/labelgover/export/excel",
    labelGoverWord: "/report/labelgover/export/word",
    perusahaan: "/report/perusahaan",
    perusahaanPdf: "/report/perusahaan/print",
    perusahaanExcel: "/report/perusahaan/export/excel",
    perusahaanWord: "/report/perusahaan/export/word",
    government: "/report/government",
    governmentPdf: "/report/government/print",
    governmentExcel: "/report/government/export/excel",
    governmentWord: "/report/government/export/word",
    jumlahPerusahaan: "/report/jumlah/perusahaan",
    jumlahPerusahaanPdf: "/report/jumlah/perusahaan/print",
    jumlahPerusahaanExcel: "/report/jumlah/perusahaan/export/excel",
    jumlahPerusahaanWord: "/report/jumlah/perusahaan/export/word",
    jumlahGovernment: "/report/jumlah/government",
    jumlahGovernmentPdf: "/report/jumlah/government/print",
    jumlahGovernmentExcel: "/report/jumlah/government/export/excel",
    jumlahGovernmentWord: "/report/jumlah/government/export/word",
    labelOptions: "/report/label/options",
  },
};
